CREATE SCHEMA LOJA_DE_GRAOS;
CREATE TABLE CLIENTES (
`id_clientes` INT NOT NULL,
`Nome`VARCHAR(100) NOT NULL,
`Numero` INT NOT NULL,
`CNPJ` VARCHAR(100) NOT NULL,
`Senha` VARCHAR(100) NOT NULL,
`Email` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_clientes)
)

SELECT * FROM  TRANSPORTADORA ;

CREATE TABLE PRODUTOS(
`id_produtos` INT NOT NULL,
`Produto` VARCHAR(100) NOT NULL,
`Quatidade` INT NOT NULL,
PRIMARY KEY(id_produtos)
)

CREATE TABLE TRANSPORTADORA (
`id_transportadora` INT NOT NULL,
`Nome` VARCHAR(150) NOT NULL,
`Numero` VARCHAR(100) NOT NULL,
`Endereço` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_transportadora)
)

CREATE TABLE ESTOQUE(
`id_estoque` INT NOT NULL,
`id_produtos
)
