CREATE SCHEMA LOJA_DE_GRAOS;
CREATE TABLE CLIENTES (
`id_clientes` INT NOT NULL,
`Nome`VARCHAR(100) NOT NULL,
`Numero` VARCHAR(100) NOT NULL,
`CNPJ` VARCHAR(100) NOT NULL,
`Senha` VARCHAR(100) NOT NULL,
`Email` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_clientes)
);

SELECT * FROM  PRODUTOS;

CREATE TABLE PRODUTOS(
`id_produtos` INT NOT NULL,
`Produto` VARCHAR(100) NOT NULL,
`Quatidade` INT NOT NULL,
PRIMARY KEY(id_produtos)
);

CREATE TABLE TRANSPORTADORA (
`id_transportadora` INT NOT NULL,
`Nome` VARCHAR(150) NOT NULL,
`Numero` VARCHAR(100) NOT NULL,
`Endereço` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_transportadora)
);

CREATE TABLE ESTOQUE(
`id_estoque` INT NOT NULL,
`id_produtos`INT NOT NULL,
`Quantidade` VARCHAR(100) NOT NULL,
`Validade` VARCHAR(100) NOT NULL,
`Preco` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_estoque)
);

ALTER TABLE ESTOQUE ADD CONSTRAINT CE_ESTOQUE_PRODUTO
FOREIGN KEY (id_produtos)
REFERENCES PRODUTOS (id_produtos)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

CREATE TABLE VENDAS (
`id_venda` INT NOT NULL,
`TOKEN` INT NOT NULL,
`Quantidade` INT NOT NULL,
`id_produtos` INT NOT NULL,
`id_clientes` INT NOT NULL,
`Endereco` VARCHAR(100) NOT NULL,
`Tempo_de_viagem` VARCHAR(100) NOT NULL,
`id_transportadora` int not null,
`Valor_Total` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_venda)
);

ALTER TABLE VENDAS ADD CONSTRAINT CE_VENDAS_PRODUTO
FOREIGN KEY (id_produtos)
REFERENCES PRODUTOS (id_produtos)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE VENDAS ADD CONSTRAINT CE_VENDAS_CLIENTES
FOREIGN KEY (id_clientes)
REFERENCES CLIENTES (id_clientes)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE VENDAS ADD CONSTRAINT CE_VENDAS_TRANPORTADORA
FOREIGN KEY (id_transportadora)
REFERENCES TRANSPORTADORA (id_transportadora)
ON DELETE NO ACTION
ON UPDATE NO ACTION;


SELECT * FROM CLIENTES;
INSERT INTO CLIENTES VALUES (
01,
'Raylane',
'(00)00000-0000',
'00.000.000/0000.0',
'raylane10',
'raylane@gmail.com'
);

INSERT INTO PRODUTOS VALUES(
(1, 'Cafe', 800000),
(2, 'Soja', 50000),
(3, 'Grao-de-bico', 40000),
(4, ' Milho', 10000)
);




