CREATE SCHEMA LOJA_DE_GRAOS;
CREATE TABLE CLIENTES (
`id_clientes` INT NOT NULL,
`Nome`VARCHAR(100) NOT NULL,
`Numero` INT NOT NULL,
`CNPJ` VARCHAR(100) NOT NULL,
`Senha` VARCHAR(100) NOT NULL,
`Email` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_clientes)
);

SELECT * FROM  VENDAS;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE PRODUTOS(
`id_produtos` INT NOT NULL,
`Produto` VARCHAR(100) NOT NULL,
`Quatidade` INT NOT NULL,
PRIMARY KEY(id_produtos)
);

CREATE TABLE TRANSPORTADORA (
`id_transportadora` INT NOT NULL,
`Nome` VARCHAR(150) NOT NULL,
`Numero` VARCHAR(100) NOT NULL,
`Endereço` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_transportadora)
);

CREATE TABLE ESTOQUE(
`id_estoque` INT NOT NULL,
`id_produtos`INT NOT NULL,
`Quantidade` VARCHAR(100) NOT NULL,
`Validade` VARCHAR(100) NOT NULL,
`Preco` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_estoque)
);

ALTER TABLE ESTOQUE ADD CONSTRAINT CE_ESTOQUE_PRODUTO
FOREIGN KEY (id_produtos)
REFERENCES PRODUTOS (id_produtos)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

CREATE TABLE VENDAS (
`id_venda` INT NOT NULL,
`TOKEN` INT NOT NULL,
`Quantidade` INT NOT NULL,
`id_produtos` INT NOT NULL,
`id_clientes` INT NOT NULL,
`Endereco` VARCHAR(100) NOT NULL,
`Tempo_de_viagem` VARCHAR(100) NOT NULL,
`id_transportadora` int not null,
`Valor_Total` VARCHAR(100) NOT NULL,
PRIMARY KEY(id_venda)
);

ALTER TABLE VENDAS ADD CONSTRAINT CE_VENDAS_PRODUTO
FOREIGN KEY (id_produtos)
REFERENCES PRODUTOS (id_produtos)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE VENDAS ADD CONSTRAINT CE_VENDAS_CLIENTES
FOREIGN KEY (id_clientes)
REFERENCES CLIENTES (id_clientes)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE VENDAS ADD CONSTRAINT CE_VENDAS_TRANPORTADORA
FOREIGN KEY (id_transportadora)
REFERENCES TRANSPORTADORA (id_transportadora)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

INSERT INTO CLIENTES VALUES(
1, "Reginaldo da Silva", (55) 99971-6529
2, "Carlinhos Matos", (55) 999569-0429
3, "Antonio Paula" (55)99984-0158